### ISSUE TITLE
Menu items work after two clicks

### ISSUE THREAD

**Issue by marco-c** [kenchris/weneed#3]
The first click doesn't do anything, the second click works.

This is both for the "Shopping list" (on the first click nothing happens, on the second click the shopping list is opened) and for the "Add random item" (on the first click nothing happens, on the second click an item is added).

**Comment by kenchris** [comment]
I cannot reproduce. I tested in both Chrome and Firefox on desktop.

**Comment by marco-c** [comment]
It is working now! Thanks!
Maybe 086199b08bc5eddef7d1f6a43e040008d79a370e fixed it.
